name: food_delivery_app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flame_audio: ^2.1.2
  http: ^1.2.2
  flutter_cache_manager: ^3.4.1
  dio: ^5.7.0
  get_storage: ^2.1.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  rive: ^0.13.15
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.11
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.4.1
  oktoast: ^3.4.0
  dio_cookie_manager: ^3.1.1
  firebase_remote_config: ^5.1.3
  url_launcher: ^6.3.1
  cookie_jar: ^4.0.8
  jwt_decoder: ^2.0.1
  audio_waveforms: ^1.1.1
  record: ^5.2.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.4
  audioplayers: ^6.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  lottie: ^3.1.3
  loadmore: ^2.1.0
  share_plus: ^10.1.2
  mime: ^2.0.0
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  flutter_launcher_icons: ^0.14.2
  connectivity_plus: ^6.1.1
  google_fonts: ^6.2.1

  hive: any
  path: any
  rxdart: any
  pin_code_fields: ^8.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900









