// ... existing imports ...
import 'package:food_delivery_app/ui/list_user_order/list_user_order.dart';
import 'package:food_delivery_app/ui/list_user_order/list_user_order_binding.dart';

// ... existing code ...

class AppPages {
  static final routes = [
    // ... existing routes ...

    // ... existing routes ...
  ];
}
